name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          user: Maty156
          token: ${{ secrets.GITHUB_TOKEN }}
          
          template: classic
          config_timezone: Africa/Addis_Ababa
          config_display: large
          
          # Base sections for clean cards
          base: header, activity, community, repositories, metadata
          
          # Languages
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          
          # Calendar + Activity
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Achievements & Highlights
          plugin_achievements: yes
          plugin_achievements_display: detailed
          
          plugin_notable: yes
          plugin_followup: yes
          plugin_followup_limit: 6
          
          # Output file
          filename: github-metrics.svg
